#cloud-config
runcmd:
  - set -x
  - apt update
  - apt upgrade -y
  - groupadd -f locust
  - useradd -m locust -g locust || echo "user already exists"
  - apt install -y htop emacs-nox wget iftop iotop python3-pip
  - pip install locust
  - echo '* - nofile 1000000' >> /etc/security/limits.conf
  - echo '* - nproc 1000000' >> /etc/security/limits.conf
  - echo ${LOCUST_FILE} | base64 -d | tee /home/locust/tasks.py
  - chown -R locust:locust /home/locust
  - |
    cat <<EOF > /lib/systemd/system/locust-master.service
    [Unit]
    Description=Locust Service
    Wants=network-online.target
    Requires=network-online.target
    After=network-online.target

    [Service]
    User=locust
    Group=locust
    Restart=always
    ExecStart=/usr/local/bin/locust -f tasks.py --master --web-auth ${LOCUST_USERNAME}:${LOCUST_PASSWORD} ${LOCUST_TAGS}
    WorkingDirectory=/home/locust
    KillSignal=SIGKILL
    SyslogIdentifier=locust
    LimitNOFILE=1000000
    LimitMEMLOCK=infinity

    [Install]
    WantedBy=multi-user.target
    EOF
  - systemctl daemon-reload
  - systemctl enable locust-master
  - systemctl restart locust-master
